spring.application.name=natillera_java
server.port=8081

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://root:root27017@mongodb:27017/natillera-java?authSource=admin

# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://sqlserver:1433;databaseName=natillera-java;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=YourStrong!Passw0rd

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


